//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService", ConfigurationName="ServiceReference1.VisionGazetteerServiceSoap")]
    public interface VisionGazetteerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetGazSearchBeforeCha" +
            "r", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGazSearchBeforeChar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetGazSearchBeforeCha" +
            "r", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGazSearchBeforeCharAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetGazSearchAfterChar" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGazSearchAfterChar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetGazSearchAfterChar" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGazSearchAfterCharAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecordTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetrieveRecordTest(string urn, bool includeSSI, bool includeLocations, bool includeLocationActions, bool includeAlarms, bool includeContacts, bool includeAdditionalData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecordTest", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordTestAsync(string urn, bool includeSSI, bool includeLocations, bool includeLocationActions, bool includeAlarms, bool includeContacts, bool includeAdditionalData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetrieveRecord(ConsoleApplication1.ServiceReference1.GazetteerRetrieveRecordArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordAsync(ConsoleApplication1.ServiceReference1.GazetteerRetrieveRecordArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchTest(string businessName, string buildingName, string buildingNumber, string streetOne, string streetTwo, string areaOne, string areaTwo, string postCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchTest", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchTestAsync(string businessName, string buildingName, string buildingNumber, string streetOne, string streetTwo, string areaOne, string areaTwo, string postCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Search(ConsoleApplication1.ServiceReference1.GazetteerStructuredSearchArgs searchArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchAsync(ConsoleApplication1.ServiceReference1.GazetteerStructuredSearchArgs searchArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchGazetteerTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchGazetteerTest(string searchText, int searchAlgorithmHint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchGazetteerTest", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchGazetteerTestAsync(string searchText, int searchAlgorithmHint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchGazetteer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchGazetteer(ConsoleApplication1.ServiceReference1.GazetteerProgressiveSearchArgs searchArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchGazetteer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchGazetteerAsync(ConsoleApplication1.ServiceReference1.GazetteerProgressiveSearchArgs searchArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/ExpandStreet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExpandStreet(ConsoleApplication1.ServiceReference1.GazetteerExpandStreetArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/ExpandStreet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExpandStreetAsync(ConsoleApplication1.ServiceReference1.GazetteerExpandStreetArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecordFromCNI" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RetrieveRecordFromCNI(int buildingNumber, string streetName1, string areaName1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/RetrieveRecordFromCNI" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordFromCNIAsync(int buildingNumber, string streetName1, string areaName1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchProgressive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ServiceReference1.sSearchDetails SearchProgressive(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, int maxHits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchProgressive", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sSearchDetails> SearchProgressiveAsync(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, int maxHits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchProgressiveExte" +
            "nded", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ServiceReference1.sSearchDetails SearchProgressiveExtended(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, bool pSoundsLike, string pArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchProgressiveExte" +
            "nded", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sSearchDetails> SearchProgressiveExtendedAsync(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, bool pSoundsLike, string pArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchExchangeArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.ServiceReference1.sExchangeArea SearchExchangeArea(string exchangeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/SearchExchangeArea", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sExchangeArea> SearchExchangeAreaAsync(string exchangeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/IsAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IsAvailable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/IsAvailable", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IsAvailableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/ResetAvailability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ResetAvailability();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisionWebServices/VisionGazetteerService/ResetAvailability", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ResetAvailabilityAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class GazetteerRetrieveRecordArgs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestIdentifier requestIdentifierField;
        
        private int counterField;
        
        private bool includeAdditionalDataField;
        
        private bool includeAlarmsField;
        
        private bool includeContactsField;
        
        private bool includeLocationsField;
        
        private bool includeLocationActionsField;
        
        private bool includeSSIField;
        
        private bool primaryField;
        
        private string uRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestIdentifier RequestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("RequestIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IncludeAdditionalData {
            get {
                return this.includeAdditionalDataField;
            }
            set {
                this.includeAdditionalDataField = value;
                this.RaisePropertyChanged("IncludeAdditionalData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IncludeAlarms {
            get {
                return this.includeAlarmsField;
            }
            set {
                this.includeAlarmsField = value;
                this.RaisePropertyChanged("IncludeAlarms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IncludeContacts {
            get {
                return this.includeContactsField;
            }
            set {
                this.includeContactsField = value;
                this.RaisePropertyChanged("IncludeContacts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IncludeLocations {
            get {
                return this.includeLocationsField;
            }
            set {
                this.includeLocationsField = value;
                this.RaisePropertyChanged("IncludeLocations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IncludeLocationActions {
            get {
                return this.includeLocationActionsField;
            }
            set {
                this.includeLocationActionsField = value;
                this.RaisePropertyChanged("IncludeLocationActions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IncludeSSI {
            get {
                return this.includeSSIField;
            }
            set {
                this.includeSSIField = value;
                this.RaisePropertyChanged("IncludeSSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
                this.RaisePropertyChanged("URN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class RequestIdentifier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientTypeField;
        
        private string positionField;
        
        private string requestIdField;
        
        private string sessionIdentifierField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
                this.RaisePropertyChanged("ClientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
                this.RaisePropertyChanged("SessionIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class sExchangeArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaNameField;
        
        private string areaCodeField;
        
        private decimal xCoordField;
        
        private decimal yCoordField;
        
        private int zoomLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AreaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
                this.RaisePropertyChanged("AreaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
                this.RaisePropertyChanged("AreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal xCoord {
            get {
                return this.xCoordField;
            }
            set {
                this.xCoordField = value;
                this.RaisePropertyChanged("xCoord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal yCoord {
            get {
                return this.yCoordField;
            }
            set {
                this.yCoordField = value;
                this.RaisePropertyChanged("yCoord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ZoomLevel {
            get {
                return this.zoomLevelField;
            }
            set {
                this.zoomLevelField = value;
                this.RaisePropertyChanged("ZoomLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class sSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fclUrnField;
        
        private long counterField;
        
        private string addressStringField;
        
        private long rankField;
        
        private string typeField;
        
        private long wordsField;
        
        private string warningFlagField;
        
        private byte primaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FclUrn {
            get {
                return this.fclUrnField;
            }
            set {
                this.fclUrnField = value;
                this.RaisePropertyChanged("FclUrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AddressString {
            get {
                return this.addressStringField;
            }
            set {
                this.addressStringField = value;
                this.RaisePropertyChanged("AddressString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Words {
            get {
                return this.wordsField;
            }
            set {
                this.wordsField = value;
                this.RaisePropertyChanged("Words");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WarningFlag {
            get {
                return this.warningFlagField;
            }
            set {
                this.warningFlagField = value;
                this.RaisePropertyChanged("WarningFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public byte Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class sSearchDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float timeField;
        
        private long hitsField;
        
        private eSearchType typeField;
        
        private string textField;
        
        private eResultType resultTypeField;
        
        private sSearchResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
                this.RaisePropertyChanged("Hits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public eSearchType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public eResultType ResultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
                this.RaisePropertyChanged("ResultType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public sSearchResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public enum eSearchType {
        
        /// <remarks/>
        eComplete,
        
        /// <remarks/>
        ePostcode,
        
        /// <remarks/>
        eOrdered,
        
        /// <remarks/>
        eAnyway,
        
        /// <remarks/>
        eCatchAll,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public enum eResultType {
        
        /// <remarks/>
        eComplete,
        
        /// <remarks/>
        eResultTimeOut,
        
        /// <remarks/>
        eQueryTimeOut,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class GazetteerExpandStreetArgs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestIdentifier requestIdentifierField;
        
        private string streetOneField;
        
        private string streetTwoField;
        
        private string areaOneField;
        
        private string areaTwoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestIdentifier RequestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("RequestIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StreetOne {
            get {
                return this.streetOneField;
            }
            set {
                this.streetOneField = value;
                this.RaisePropertyChanged("StreetOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StreetTwo {
            get {
                return this.streetTwoField;
            }
            set {
                this.streetTwoField = value;
                this.RaisePropertyChanged("StreetTwo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AreaOne {
            get {
                return this.areaOneField;
            }
            set {
                this.areaOneField = value;
                this.RaisePropertyChanged("AreaOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AreaTwo {
            get {
                return this.areaTwoField;
            }
            set {
                this.areaTwoField = value;
                this.RaisePropertyChanged("AreaTwo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class GazetteerProgressiveSearchArgs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestIdentifier requestIdentifierField;
        
        private int searchAlgorithmHintField;
        
        private string searchTextField;
        
        private int maxPremiseHitsField;
        
        private int maxStreetHitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestIdentifier RequestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("RequestIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SearchAlgorithmHint {
            get {
                return this.searchAlgorithmHintField;
            }
            set {
                this.searchAlgorithmHintField = value;
                this.RaisePropertyChanged("SearchAlgorithmHint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SearchText {
            get {
                return this.searchTextField;
            }
            set {
                this.searchTextField = value;
                this.RaisePropertyChanged("SearchText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int MaxPremiseHits {
            get {
                return this.maxPremiseHitsField;
            }
            set {
                this.maxPremiseHitsField = value;
                this.RaisePropertyChanged("MaxPremiseHits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MaxStreetHits {
            get {
                return this.maxStreetHitsField;
            }
            set {
                this.maxStreetHitsField = value;
                this.RaisePropertyChanged("MaxStreetHits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public partial class GazetteerStructuredSearchArgs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestIdentifier requestIdentifierField;
        
        private SearchType searchTypeField;
        
        private bool exactMatchField;
        
        private string alarmCodeField;
        
        private string contactNumberField;
        
        private string businessNameField;
        
        private string buildingNameField;
        
        private string buildingNumberField;
        
        private string streetOneField;
        
        private string streetTwoField;
        
        private string areaOneField;
        
        private string areaTwoField;
        
        private string postCodeField;
        
        private string owningCodeField;
        
        private string categoryField;
        
        private bool phoneticField;
        
        private bool stripSearchField;
        
        private float vicinityXField;
        
        private float vicinityYField;
        
        private float vicinityWidthField;
        
        private float vicinityHeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestIdentifier RequestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("RequestIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SearchType SearchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
                this.RaisePropertyChanged("SearchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ExactMatch {
            get {
                return this.exactMatchField;
            }
            set {
                this.exactMatchField = value;
                this.RaisePropertyChanged("ExactMatch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AlarmCode {
            get {
                return this.alarmCodeField;
            }
            set {
                this.alarmCodeField = value;
                this.RaisePropertyChanged("AlarmCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContactNumber {
            get {
                return this.contactNumberField;
            }
            set {
                this.contactNumberField = value;
                this.RaisePropertyChanged("ContactNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BusinessName {
            get {
                return this.businessNameField;
            }
            set {
                this.businessNameField = value;
                this.RaisePropertyChanged("BusinessName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
                this.RaisePropertyChanged("BuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
                this.RaisePropertyChanged("BuildingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StreetOne {
            get {
                return this.streetOneField;
            }
            set {
                this.streetOneField = value;
                this.RaisePropertyChanged("StreetOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetTwo {
            get {
                return this.streetTwoField;
            }
            set {
                this.streetTwoField = value;
                this.RaisePropertyChanged("StreetTwo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AreaOne {
            get {
                return this.areaOneField;
            }
            set {
                this.areaOneField = value;
                this.RaisePropertyChanged("AreaOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AreaTwo {
            get {
                return this.areaTwoField;
            }
            set {
                this.areaTwoField = value;
                this.RaisePropertyChanged("AreaTwo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string OwningCode {
            get {
                return this.owningCodeField;
            }
            set {
                this.owningCodeField = value;
                this.RaisePropertyChanged("OwningCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Phonetic {
            get {
                return this.phoneticField;
            }
            set {
                this.phoneticField = value;
                this.RaisePropertyChanged("Phonetic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool StripSearch {
            get {
                return this.stripSearchField;
            }
            set {
                this.stripSearchField = value;
                this.RaisePropertyChanged("StripSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public float VicinityX {
            get {
                return this.vicinityXField;
            }
            set {
                this.vicinityXField = value;
                this.RaisePropertyChanged("VicinityX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public float VicinityY {
            get {
                return this.vicinityYField;
            }
            set {
                this.vicinityYField = value;
                this.RaisePropertyChanged("VicinityY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public float VicinityWidth {
            get {
                return this.vicinityWidthField;
            }
            set {
                this.vicinityWidthField = value;
                this.RaisePropertyChanged("VicinityWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public float VicinityHeight {
            get {
                return this.vicinityHeightField;
            }
            set {
                this.vicinityHeightField = value;
                this.RaisePropertyChanged("VicinityHeight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/VisionWebServices/VisionGazetteerService")]
    public enum SearchType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Premise,
        
        /// <remarks/>
        Street,
        
        /// <remarks/>
        Area,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VisionGazetteerServiceSoapChannel : ConsoleApplication1.ServiceReference1.VisionGazetteerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisionGazetteerServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.VisionGazetteerServiceSoap>, ConsoleApplication1.ServiceReference1.VisionGazetteerServiceSoap {
        
        public VisionGazetteerServiceSoapClient() {
        }
        
        public VisionGazetteerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisionGazetteerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisionGazetteerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisionGazetteerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGazSearchBeforeChar() {
            return base.Channel.GetGazSearchBeforeChar();
        }
        
        public System.Threading.Tasks.Task<string> GetGazSearchBeforeCharAsync() {
            return base.Channel.GetGazSearchBeforeCharAsync();
        }
        
        public string GetGazSearchAfterChar() {
            return base.Channel.GetGazSearchAfterChar();
        }
        
        public System.Threading.Tasks.Task<string> GetGazSearchAfterCharAsync() {
            return base.Channel.GetGazSearchAfterCharAsync();
        }
        
        public System.Data.DataSet RetrieveRecordTest(string urn, bool includeSSI, bool includeLocations, bool includeLocationActions, bool includeAlarms, bool includeContacts, bool includeAdditionalData) {
            return base.Channel.RetrieveRecordTest(urn, includeSSI, includeLocations, includeLocationActions, includeAlarms, includeContacts, includeAdditionalData);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordTestAsync(string urn, bool includeSSI, bool includeLocations, bool includeLocationActions, bool includeAlarms, bool includeContacts, bool includeAdditionalData) {
            return base.Channel.RetrieveRecordTestAsync(urn, includeSSI, includeLocations, includeLocationActions, includeAlarms, includeContacts, includeAdditionalData);
        }
        
        public System.Data.DataSet RetrieveRecord(ConsoleApplication1.ServiceReference1.GazetteerRetrieveRecordArgs args) {
            return base.Channel.RetrieveRecord(args);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordAsync(ConsoleApplication1.ServiceReference1.GazetteerRetrieveRecordArgs args) {
            return base.Channel.RetrieveRecordAsync(args);
        }
        
        public System.Data.DataSet SearchTest(string businessName, string buildingName, string buildingNumber, string streetOne, string streetTwo, string areaOne, string areaTwo, string postCode) {
            return base.Channel.SearchTest(businessName, buildingName, buildingNumber, streetOne, streetTwo, areaOne, areaTwo, postCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchTestAsync(string businessName, string buildingName, string buildingNumber, string streetOne, string streetTwo, string areaOne, string areaTwo, string postCode) {
            return base.Channel.SearchTestAsync(businessName, buildingName, buildingNumber, streetOne, streetTwo, areaOne, areaTwo, postCode);
        }
        
        public System.Data.DataSet Search(ConsoleApplication1.ServiceReference1.GazetteerStructuredSearchArgs searchArgs) {
            return base.Channel.Search(searchArgs);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchAsync(ConsoleApplication1.ServiceReference1.GazetteerStructuredSearchArgs searchArgs) {
            return base.Channel.SearchAsync(searchArgs);
        }
        
        public System.Data.DataSet SearchGazetteerTest(string searchText, int searchAlgorithmHint) {
            return base.Channel.SearchGazetteerTest(searchText, searchAlgorithmHint);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchGazetteerTestAsync(string searchText, int searchAlgorithmHint) {
            return base.Channel.SearchGazetteerTestAsync(searchText, searchAlgorithmHint);
        }
        
        public System.Data.DataSet SearchGazetteer(ConsoleApplication1.ServiceReference1.GazetteerProgressiveSearchArgs searchArgs) {
            return base.Channel.SearchGazetteer(searchArgs);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchGazetteerAsync(ConsoleApplication1.ServiceReference1.GazetteerProgressiveSearchArgs searchArgs) {
            return base.Channel.SearchGazetteerAsync(searchArgs);
        }
        
        public System.Data.DataSet ExpandStreet(ConsoleApplication1.ServiceReference1.GazetteerExpandStreetArgs args) {
            return base.Channel.ExpandStreet(args);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExpandStreetAsync(ConsoleApplication1.ServiceReference1.GazetteerExpandStreetArgs args) {
            return base.Channel.ExpandStreetAsync(args);
        }
        
        public System.Data.DataSet RetrieveRecordFromCNI(int buildingNumber, string streetName1, string areaName1) {
            return base.Channel.RetrieveRecordFromCNI(buildingNumber, streetName1, areaName1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RetrieveRecordFromCNIAsync(int buildingNumber, string streetName1, string areaName1) {
            return base.Channel.RetrieveRecordFromCNIAsync(buildingNumber, streetName1, areaName1);
        }
        
        public System.Data.DataSet GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.sSearchDetails SearchProgressive(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, int maxHits) {
            return base.Channel.SearchProgressive(searchText, searchType, maxHits);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sSearchDetails> SearchProgressiveAsync(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, int maxHits) {
            return base.Channel.SearchProgressiveAsync(searchText, searchType, maxHits);
        }
        
        public ConsoleApplication1.ServiceReference1.sSearchDetails SearchProgressiveExtended(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, bool pSoundsLike, string pArea) {
            return base.Channel.SearchProgressiveExtended(searchText, searchType, pSoundsLike, pArea);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sSearchDetails> SearchProgressiveExtendedAsync(string searchText, ConsoleApplication1.ServiceReference1.eSearchType searchType, bool pSoundsLike, string pArea) {
            return base.Channel.SearchProgressiveExtendedAsync(searchText, searchType, pSoundsLike, pArea);
        }
        
        public ConsoleApplication1.ServiceReference1.sExchangeArea SearchExchangeArea(string exchangeNumber) {
            return base.Channel.SearchExchangeArea(exchangeNumber);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.sExchangeArea> SearchExchangeAreaAsync(string exchangeNumber) {
            return base.Channel.SearchExchangeAreaAsync(exchangeNumber);
        }
        
        public int IsAvailable() {
            return base.Channel.IsAvailable();
        }
        
        public System.Threading.Tasks.Task<int> IsAvailableAsync() {
            return base.Channel.IsAvailableAsync();
        }
        
        public int ResetAvailability() {
            return base.Channel.ResetAvailability();
        }
        
        public System.Threading.Tasks.Task<int> ResetAvailabilityAsync() {
            return base.Channel.ResetAvailabilityAsync();
        }
    }
}
